
services:
  mongodb:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    networks:
      - chat-ui
  ollama-service:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama
    networks:
      - chat-ui
  chat-ui:
    image: ghcr.io/huggingface/chat-ui-db:latest
    volumes:
    - ./db:/data
    - ./.env.local/.env.local:/app/.env.local  # Ensure this path exists and is correct
    env_file:
     - .env.local/.env.local  # This should be the correct file reference
    ports:
      - 3000:3000
    depends_on:
      - mongodb # Ensure chat-ui starts after MongoDB
      - ollama-service  # Ensure chat-ui starts after ollama-service
    networks:
      - chat-ui

networks:
  chat-ui:
    driver: bridge